uniffi::setup_scaffolding!();

mod auto_redact;
mod cms_sign;
mod compare;
mod compress;
mod content_util;
mod convert;
mod forms;
mod info;
mod markdown;
mod merge;
mod metadata;
mod ocr;
mod overlay;
mod page_numbers;
mod pages;
mod pfx;
mod pfx_generate;
pub(crate) mod rasterize;
pub(crate) mod redact;
mod rotate;
mod sanitize;
mod security;
pub(crate) mod sign;
mod split;
mod stamp;
mod watermark;

pub use auto_redact::content_auto_redact;
pub use compare::{tool_compare, PageComparison};
pub use compress::{compress_pdf_by_level, compress_pdf_custom, compress_pdf_to_target_size};
pub use convert::convert_images_to_pdf;
pub use forms::{forms_fill, forms_flatten, forms_get_fields, FieldFill, FormField};
pub use info::{describe_images, get_page_count};
pub use markdown::convert_markdown_to_html;
pub use merge::{merge_pdfs, EngineError};
pub use metadata::{metadata_edit, metadata_extract, PdfMetadata};
pub use ocr::{ocr_apply_text_layer, OcrPage, OcrWord};
pub use overlay::tool_overlay;
pub use page_numbers::content_page_numbers;
pub use pages::{extract_pages, pages_crop, pages_n_up, pages_reorder, pages_scale, remove_pages};
pub use pfx_generate::generate_self_signed_pfx;
pub use rasterize::convert_pdf_to_images;
pub use redact::{content_redact, RedactionArea};
pub use rotate::rotate_pdf;
pub use sanitize::security_sanitize;
pub use security::{add_password, remove_password};
pub use sign::{certify_pdf, sign_pdf};
pub use split::split_pdf;
pub use stamp::stamp_signature_image;
pub use watermark::{content_watermark_image, content_watermark_text};
